# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 721fad5c6929ca22aff3f1cb69c17fcdb0911913462e0859ca8c560feb3cb4303675a1838f0b8ef1d97ddac844804a6be1e1e58fd23105d1e08121c66592fdba

test:
  secret_key_base: e64b0aefef456fd8432fee077f122c936876fb42c9488ce8f1a34ef881f404e750ea2afebbf8de9437365366b89430a811e9f4d3704dc00c2bb307b936743471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
